# Generated by Django 3.1.5 on 2021-01-19 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_img', models.ImageField(upload_to='img')),
            ],
            options={
                'db_table': 'headers',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img')),
                ('text', models.CharField(max_length=100)),
                ('button_text', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'heros',
            },
        ),
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=70)),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.header')),
            ],
            options={
                'db_table': 'landings',
            },
        ),
        migrations.CreateModel(
            name='NavbarContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'navbar_contacts',
            },
        ),
        migrations.CreateModel(
            name='NavbarMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'navbar_menus',
            },
        ),
        migrations.CreateModel(
            name='RowBlock2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sorting', models.PositiveSmallIntegerField(default=0)),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.landing')),
            ],
            options={
                'verbose_name': 'Row_Block_2',
                'verbose_name_plural': 'Row_Blocks_2',
                'db_table': 'row_blocks_2',
                'ordering': ['sorting'],
            },
        ),
        migrations.CreateModel(
            name='RowBlock1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sorting', models.PositiveSmallIntegerField(default=0)),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.landing')),
            ],
            options={
                'verbose_name': 'Row_Block_1',
                'verbose_name_plural': 'Row_Blocks_1',
                'db_table': 'row_blocks_1',
                'ordering': ['sorting'],
            },
        ),
        migrations.CreateModel(
            name='Percent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.CharField(max_length=100)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.rowblock1')),
            ],
            options={
                'db_table': 'percents',
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.rowblock1')),
            ],
            options={
                'db_table': 'paragraphs',
            },
        ),
        migrations.CreateModel(
            name='NavbarMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=200)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.navbarmenu')),
            ],
            options={
                'db_table': 'navbar_menu_items',
            },
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='img')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.navbarcontact')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.navbarmenu')),
            ],
            options={
                'db_table': 'navbars',
            },
        ),
        migrations.AddField(
            model_name='header',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.hero'),
        ),
        migrations.AddField(
            model_name='header',
            name='navbar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.navbar'),
        ),
        migrations.CreateModel(
            name='ColumnBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sorting', models.PositiveSmallIntegerField(default=0)),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.landing')),
            ],
            options={
                'verbose_name': 'Column_block',
                'verbose_name_plural': 'Column_blocks',
                'db_table': 'column_blocks',
                'ordering': ['sorting'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='img')),
                ('footer', models.CharField(max_length=100)),
                ('background', models.CharField(blank=True, choices=[('', ''), ('bg-blue', 'blue'), ('bg-purple-gradient', 'purple-gradient'), ('bg-marina', 'marina')], max_length=30, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.columnblock')),
            ],
            options={
                'db_table': 'cards',
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img')),
                ('text', models.CharField(max_length=200)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.rowblock2')),
            ],
            options={
                'db_table': 'benefits',
            },
        ),
    ]
